---
# Ansible Galaxy collection requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: cloud.terraform
    version: ">=1.1.0"
  
  - name: kubernetes.core
    version: ">=3.0.0"
  
  - name: community.general
    version: ">=8.0.0"

